import type { Requirement } from './domain'
import { artifactPortion, portionText, systemHigh } from './marking'
import {
  type AnalysisRow,
  type PackageFile,
  type TwinArtifact,
  affectedSubsystems,
  analysisRows,
  limitLabel,
  twinArtifacts,
  twinChanges,
  twinRevision,
  withinLimit,
} from './twin'
import { crc32 } from './zip'

const cell = (value: string): string => value.replaceAll('|', '\\|')
const csv = (value: string): string => `"${value.replaceAll('"', '""')}"`
const checksum = (value: string): string =>
  (crc32(new TextEncoder().encode(value)) >>> 0)
    .toString(16)
    .toUpperCase()
    .padStart(8, '0')

export const do254DocumentId = (
  prefix: 'HAS' | 'HCI' | 'HVR' | 'CIA',
  requirements: ReadonlyArray<Requirement>,
): string => `${prefix}-PSU-001-Rev${twinRevision(requirements)}`

const partNumber = (requirements: ReadonlyArray<Requirement>): string =>
  twinRevision(requirements) === 'B' ? 'MW-MPA-48-5' : 'MW-MPA-48-4'

const logicImage = (requirements: ReadonlyArray<Requirement>): string =>
  twinRevision(requirements) === 'B'
    ? 'PSU-SEQ FPGA image v2.1.0'
    : 'PSU-SEQ FPGA image v1.4.2'

const header = (
  title: string,
  document: string,
  reference: string,
  requirements: ReadonlyArray<Requirement>,
  date: string,
): ReadonlyArray<string> => [
  `**${systemHigh}**`,
  '',
  `# ${title} — Aft Modular Power Assembly`,
  '',
  `Document: ${document} · Date: ${date} · Hardware item: ${partNumber(requirements)} · ${reference}`,
  '',
  '> (U) Generated by Stream from the systems model. DRAFT, not for submission to a certification authority until the sign-offs below are complete. Part numbers, design assurance level, and markings are notional for demonstration.',
  '',
]

const footer = [`**${systemHigh}**`, '']

const current = (
  requirements: ReadonlyArray<Requirement>,
  id: string,
): Requirement | undefined => requirements.find(item => item.id === id)

export type ProblemReport = Readonly<{
  id: string
  title: string
  category: 'Design' | 'Verification'
  source: string
  status: 'Open'
  action: string
}>

const marginFraction = (row: AnalysisRow): number =>
  row.limit.value === 0
    ? Number.POSITIVE_INFINITY
    : Math.abs(row.revB - row.limit.value) / Math.abs(row.limit.value)

const headroom = (row: AnalysisRow, value: number): number =>
  row.limit.kind === 'Max' ? row.limit.value - value : value - row.limit.value

const marginReduced = (row: AnalysisRow): boolean =>
  headroom(row, row.revB) < headroom(row, row.revA)

const unitSuffix = (row: AnalysisRow): string =>
  row.unit ? ` ${row.unit}` : ''

export const problemReports = (
  requirements: ReadonlyArray<Requirement>,
): ReadonlyArray<ProblemReport> => {
  if (twinRevision(requirements) === 'A') {
    return []
  }
  const analysis = analysisRows
    .filter(
      row =>
        !withinLimit(row, row.revB) ||
        (marginFraction(row) < 0.1 &&
          (row.revB === row.limit.value || marginReduced(row))),
    )
    .map(row => ({
      title: withinLimit(row, row.revB)
        ? `Low margin: ${row.metric} ${row.revB}${unitSuffix(row)} against ${limitLabel(row)}`
        : `Exceeds limit: ${row.metric} ${row.revB}${unitSuffix(row)} against ${limitLabel(row)}`,
      category: 'Design' as const,
      source: `${row.domain} analysis`,
      action:
        'Confirm by qualification test; disposition at the Rev B design review.',
    }))
  const tests = twinChanges(requirements)
    .filter(
      change => change.artifact.kind === 'Test' && change.status !== 'Verified',
    )
    .map(change => ({
      title: `${change.artifact.id} qualification evidence pending for Rev B`,
      category: 'Verification' as const,
      source: change.artifact.id,
      action:
        'Run the HVP test procedures and record results per DO-254 §10.4.5.',
    }))
  return [...analysis, ...tests].map((item, index): ProblemReport => ({
    id: `PR-PSU-${String(141 + index).padStart(4, '0')}`,
    title: item.title,
    category: item.category,
    source: item.source,
    status: 'Open',
    action: item.action,
  }))
}

const verificationResult = (
  artifact: TwinArtifact,
  item: Requirement | undefined,
): string =>
  !item
    ? 'Not in model'
    : item.status === 'Verified'
      ? `Complete (r${item.revision})`
      : artifact.verification === 'Analysis'
        ? 'Analysis within limits · review open'
        : artifact.verification === 'Test'
          ? 'Open · TST-PSU not yet run on Rev B'
          : 'Open · first-article inspection of Rev B'

const requirementRows = twinArtifacts.filter(
  item => item.kind === 'Requirement',
)

const verificationSummary = (
  requirements: ReadonlyArray<Requirement>,
): Readonly<{ total: number; complete: number; traced: number }> => ({
  total: requirementRows.length,
  complete: requirementRows.filter(
    item => current(requirements, item.id)?.status === 'Verified',
  ).length,
  traced: requirementRows.filter(item => item.links.length > 0).length,
})

const procedureFor = (artifact: TwinArtifact): string =>
  artifact.verification === 'Test'
    ? 'HVP-PSU-001 §4 · TST-PSU'
    : artifact.verification === 'Analysis'
      ? 'HVP-PSU-001 §5 · thermal analysis'
      : 'HVP-PSU-001 §6 · inspection checklist'

export const verificationResultsDocument = (
  requirements: ReadonlyArray<Requirement>,
  date: string,
): string => {
  const summary = verificationSummary(requirements)
  const test = current(requirements, 'TST-PSU')
  const testDone = test?.status === 'Verified'
  return [
    ...header(
      'Hardware Verification Results',
      do254DocumentId('HVR', requirements),
      'DO-254 §10.4.1, §10.4.3, §10.4.5',
      requirements,
      date,
    ),
    '## 1. Scope',
    '',
    '(U) Review and analysis results (DO-254 §10.4.3), test results (§10.4.5), and the traceability analysis (§10.4.1) for the hardware requirements in HRD-PSU-001. Procedures are defined in the Hardware Verification Plan, HVP-PSU-001.',
    '',
    '## 2. Requirements-based verification',
    '',
    '| ID | Requirement | Method | Procedure | Result |',
    '| --- | --- | --- | --- | --- |',
    ...requirementRows.map(
      artifact =>
        `| ${artifact.id} | ${portionText(artifactPortion(artifact))} ${cell(current(requirements, artifact.id)?.description ?? artifact.revA)} | ${artifact.verification} | ${procedureFor(artifact)} | ${verificationResult(artifact, current(requirements, artifact.id))} |`,
    ),
    '',
    '## 3. Review & analysis results',
    '',
    '| Metric | Domain | Rev A | Rev B | Limit | Margin | Result |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...analysisRows.map(
      row =>
        `| ${row.metric} | ${row.domain} | ${row.revA} | ${row.revB} | ${limitLabel(row)} | ${Number.isFinite(marginFraction(row)) ? `${(marginFraction(row) * 100).toFixed(1)} %` : `${row.revB}`} | ${withinLimit(row, row.revB) ? 'Pass' : 'Fail'} |`,
    ),
    '',
    '## 4. Test results',
    '',
    '| Field | Record |',
    '| --- | --- |',
    '| Procedure | HVP-PSU-001 §4 · TST-PSU thermal soak and random vibration |',
    `| Item tested | ${partNumber(requirements)} · ${logicImage(requirements)} |`,
    `| Actual results | ${testDone ? 'Recorded in TST-PSU evidence' : 'Not yet run on this configuration'} |`,
    `| Conducted by / witnessed by | ${testDone ? 'Jordan Lee / process assurance' : '— / —'} |`,
    `| Date | ${testDone ? date : '—'} |`,
    `| Coverage achieved | ${testDone ? 'All test-verified requirements' : 'None for Rev B; Rev A evidence does not cover the 5-module, 12 kW N−1 configuration'} |`,
    '',
    '## 5. Traceability analysis',
    '',
    '| System requirement | Hardware requirement | Design / interface | Verification |',
    '| --- | --- | --- | --- |',
    ...requirementRows.map(
      item =>
        `| SYS-EPS | ${item.id} | ${item.links.filter(id => !id.startsWith('TST-')).join(', ') || '—'} | ${item.links.filter(id => id.startsWith('TST-')).join(', ') || procedureFor(item)} |`,
    ),
    '',
    `(U) ${summary.traced} of ${summary.total} hardware requirements trace up to SYS-EPS and down to design and verification data. ${summary.traced === summary.total ? 'No untraced requirements were found.' : `${summary.total - summary.traced} requirements have no downstream trace.`} No derived requirements are introduced by Rev B.`,
    '',
    '## 6. Summary',
    '',
    `- Requirements verified: ${summary.complete} of ${summary.total}`,
    `- Open problem reports: ${problemReports(requirements).length} (see problem-reports.csv)`,
    '',
    ...footer,
  ].join('\n')
}

const affectedData = (artifact: TwinArtifact): string =>
  artifact.kind === 'Requirement'
    ? 'HRD-PSU-001 (§10.3.1); HVR-PSU-001'
    : artifact.kind === 'Design'
      ? 'Detailed design data (§10.3.2); HCI-PSU-001'
      : artifact.kind === 'Interface'
        ? 'Interface control data; HRD-PSU-001 §5'
        : artifact.kind === 'Test'
          ? 'Test procedures (§10.4.4); test results (§10.4.5)'
          : 'System allocation to hardware'

export const changeImpactDocument = (
  requirements: ReadonlyArray<Requirement>,
  date: string,
): string => {
  const changes = twinChanges(requirements)
  const changedIds = new Set(changes.map(change => change.artifact.id))
  const unchanged = twinArtifacts.filter(item => !changedIds.has(item.id))
  return [
    ...header(
      'Change Impact Analysis',
      do254DocumentId('CIA', requirements),
      'DO-254 §11.1',
      requirements,
      date,
    ),
    '## 1. Purpose',
    '',
    changes.length > 0
      ? `(U) Assesses the impact of the Rev A → Rev B modification to previously developed hardware (DO-254 §11.1), identifies the life cycle data to update, and defines the re-verification needed. ${changes.length} artifacts in the systems model changed.`
      : '(U) No change from the Rev A baseline. No impact.',
    '',
    '## 2. Change classification',
    '',
    changes.length > 0
      ? '(U) Proposed: **Major**. Converter modules rise from 4 to 5 to restore N−1 capacity for the cockpit avionics upgrade (ECP-0219), and the thermal, electrical, and structural interfaces change. Certification authority concurrence is required.'
      : '(U) Not applicable.',
    '',
    '## 3. Changed items',
    '',
    '| ID | Kind | Subsystem | Rev | After change | Affected life cycle data | Re-verification |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...changes.map(
      change =>
        `| ${change.artifact.id} | ${change.artifact.kind} | ${change.artifact.subsystem} | r${change.revision} | ${cell(change.after)} | ${affectedData(change.artifact)} | ${change.artifact.verification} |`,
    ),
    '',
    '## 4. Affected subsystems',
    '',
    ...affectedSubsystems(changes).map(
      item => `- ${item.name}: ${item.ids.join(', ')}`,
    ),
    '',
    '## 5. Analysis deltas',
    '',
    '| Metric | Rev A | Rev B | Limit | Margin trend |',
    '| --- | --- | --- | --- | --- |',
    ...analysisRows.map(row => {
      const gainA =
        row.limit.kind === 'Max'
          ? row.limit.value - row.revA
          : row.revA - row.limit.value
      const gainB =
        row.limit.kind === 'Max'
          ? row.limit.value - row.revB
          : row.revB - row.limit.value
      return `| ${row.metric} | ${row.revA} | ${row.revB} | ${limitLabel(row)} | ${gainB < gainA ? 'Reduced' : gainB > gainA ? 'Improved' : 'Unchanged'} |`
    }),
    '',
    '## 6. Unchanged items',
    '',
    unchanged.length > 0
      ? `(U) ${unchanged.map(item => item.id).join(', ')} are unchanged. They are covered by regression analysis against the changed interfaces; no re-verification is planned.`
      : '(U) None.',
    '',
    ...footer,
  ].join('\n')
}

export const configurationIndexDocument = (
  requirements: ReadonlyArray<Requirement>,
  date: string,
): string => {
  const rev = twinRevision(requirements)
  const design = current(requirements, 'DES-PSU')?.description ?? ''
  const lifeCycle: ReadonlyArray<readonly [string, string, string, string]> = [
    [
      'PHAC-PSU-001',
      'Plan for Hardware Aspects of Certification',
      '§10.1.1',
      rev === 'B' ? 'Rev B (change supplement)' : 'Rev A',
    ],
    ['HDP-PSU-001', 'Hardware Design Plan', '§10.1.2', 'Rev A'],
    ['HVP-PSU-001', 'Hardware Verification Plan', '§10.1.4', 'Rev A'],
    [
      'HCMP-PSU-001',
      'Hardware Configuration Management Plan',
      '§10.1.5',
      'Rev A',
    ],
    ['HPAP-PSU-001', 'Hardware Process Assurance Plan', '§10.1.6', 'Rev A'],
    ['HRD-PSU-001', 'Hardware Requirements', '§10.3.1', `Rev ${rev}`],
    ['HDD-PSU-001', 'Detailed Design Data', '§10.3.2.2', `Rev ${rev}`],
    [
      'TRC-PSU-001',
      'Traceability Data (traceability.csv)',
      '§10.4.1',
      `Rev ${rev}`,
    ],
    [
      'HVR-PSU-001',
      'Review, Analysis and Test Results',
      '§10.4.3, §10.4.5',
      `Rev ${rev}`,
    ],
    [
      'PRL-PSU-001',
      'Problem Reports (problem-reports.csv)',
      '§10.6',
      `${problemReports(requirements).length} open`,
    ],
    ['CIA-PSU-001', 'Change Impact Analysis', '§11.1', `Rev ${rev}`],
    [
      'HAS-PSU-001',
      'Hardware Accomplishment Summary',
      '§10.9',
      `Rev ${rev} (draft)`,
    ],
  ]
  return [
    ...header(
      'Hardware Configuration Index',
      do254DocumentId('HCI', requirements),
      'Top-level drawing, DO-254 §10.3.2.2.1 / AC 20-152A §5.10',
      requirements,
      date,
    ),
    '## 1. Hardware item',
    '',
    '| Field | Value |',
    '| --- | --- |',
    `| Top-level part number | ${partNumber(requirements)} Rev ${rev} |`,
    `| Description | ${cell(design)} |`,
    `| Circuit board assembly | MW-CCA-0412 Rev ${rev} |`,
    `| Complex custom device | PSU sequencing & protection FPGA |`,
    `| Embedded logic | ${logicImage(requirements)} · CRC-32 ${checksum(design)} |`,
    '| Life cycle environment | HECI-PSU-001 Rev A (unchanged) |',
    '',
    '## 2. Hardware life cycle data',
    '',
    '| Document | Title | DO-254 | Revision |',
    '| --- | --- | --- | --- |',
    ...lifeCycle.map(row => `| ${row.join(' | ')} |`),
    '',
    '## 3. Changes from the previous configuration',
    '',
    ...(twinChanges(requirements).length > 0
      ? twinChanges(requirements).map(
          change =>
            `- ${change.artifact.id} → r${change.revision} (${change.status})`,
        )
      : ['- None. This is the baseline configuration.']),
    '',
    ...footer,
  ].join('\n')
}

export const accomplishmentSummaryDocument = (
  requirements: ReadonlyArray<Requirement>,
  date: string,
): string => {
  const rev = twinRevision(requirements)
  const reports = problemReports(requirements)
  const summary = verificationSummary(requirements)
  const changes = twinChanges(requirements)
  const outstanding = summary.total - summary.complete
  const canClaim = reports.length === 0 && outstanding === 0
  return [
    ...header(
      'Hardware Accomplishment Summary',
      do254DocumentId('HAS', requirements),
      'DO-254 §10.9',
      requirements,
      date,
    ),
    '## 1. System & hardware overview',
    '',
    `(U) ${current(requirements, 'SYS-EPS')?.description ?? ''}`,
    '',
    '| Field | Value |',
    '| --- | --- |',
    `| Hardware item | ${partNumber(requirements)} Rev ${rev} (see ${do254DocumentId('HCI', requirements)}) |`,
    '| Hardware type | Circuit board assembly with one complex custom device (FPGA) |',
    '| Design assurance level | Level A (notional; set by the system safety assessment) |',
    '| Guidance | RTCA DO-254 / EUROCAE ED-80 with AC 20-152A objectives as tailored in PHAC-PSU-001 |',
    '| Airworthiness authority | Program military airworthiness authority (notional) |',
    '',
    '## 2. Stages of involvement',
    '',
    '| Review | Scope | Status |',
    '| --- | --- | --- |',
    `| SOI#1 | Planning: PHAC change supplement | ${rev === 'B' ? 'Planned' : 'Complete (Rev A)'} |`,
    `| SOI#2 | Design: requirements, design, implementation | ${rev === 'B' ? 'Not started' : 'Complete (Rev A)'} |`,
    `| SOI#3 | Validation & verification | ${rev === 'B' ? 'Not started' : 'Complete (Rev A)'} |`,
    `| SOI#4 | Final: conformity review, HAS, HCI | ${rev === 'B' ? 'Not started' : 'Complete (Rev A)'} |`,
    '',
    '## 3. Change summary',
    '',
    changes.length > 0
      ? `(U) Rev ${rev} changes ${changes.length} artifacts. See ${do254DocumentId('CIA', requirements)} for the impact analysis.`
      : '(U) Baseline issue, no changes.',
    '',
    ...changes.map(
      change =>
        `- ${change.artifact.id} (r${change.revision}): ${change.after}`,
    ),
    '',
    '## 4. Compliance status',
    '',
    `- Requirements verified: ${summary.complete} of ${summary.total}`,
    `- Requirements traced: ${summary.traced} of ${summary.total}`,
    `- Open problem reports: ${reports.length}`,
    '- Hardware conformity review: not yet performed',
    '',
    reports.length > 0 ? '| Problem report | Category | Title | Status |' : '',
    reports.length > 0 ? '| --- | --- | --- | --- |' : '',
    ...reports.map(
      item =>
        `| ${item.id} | ${item.category} | ${cell(item.title)} | ${item.status} |`,
    ),
    '',
    '## 5. Deviations from the PHAC',
    '',
    '(U) None identified.',
    '',
    '## 6. Compliance statement',
    '',
    canClaim
      ? '(U) The hardware item complies with PHAC-PSU-001 and the applicable DO-254 objectives.'
      : `(U) Compliance is not yet claimed. ${outstanding} requirements await re-verification and ${reports.length} problem reports are open. This summary will be reissued for SOI#4.`,
    '',
    '## 7. Sign-off',
    '',
    '| Role | Name | Signature | Date |',
    '| --- | --- | --- | --- |',
    '| Hardware lead | | | |',
    '| Verification lead | | | |',
    '| Process assurance | | | |',
    '| Certification liaison | | | |',
    '',
    ...footer,
  ].join('\n')
}

export const problemReportsCsv = (
  requirements: ReadonlyArray<Requirement>,
): string =>
  [
    ['ID', 'Category', 'Title', 'Source', 'Status', 'Corrective action'],
    ...problemReports(requirements).map(item => [
      item.id,
      item.category,
      item.title,
      item.source,
      item.status,
      item.action,
    ]),
  ]
    .map(row => row.map(csv).join(','))
    .join('\n')

export const do254Files = (
  requirements: ReadonlyArray<Requirement>,
  date: string,
): ReadonlyArray<PackageFile> => [
  {
    name: `${do254DocumentId('HAS', requirements)}.md`,
    content: accomplishmentSummaryDocument(requirements, date),
  },
  {
    name: `${do254DocumentId('HCI', requirements)}.md`,
    content: configurationIndexDocument(requirements, date),
  },
  {
    name: `${do254DocumentId('HVR', requirements)}.md`,
    content: verificationResultsDocument(requirements, date),
  },
  {
    name: `${do254DocumentId('CIA', requirements)}.md`,
    content: changeImpactDocument(requirements, date),
  },
  { name: 'problem-reports.csv', content: problemReportsCsv(requirements) },
]
