import { Schema } from 'effect'
import { defineMessageUnion } from 'foldkit/message'

import {
  AgentWave,
  ArtifactField,
  ArtifactView,
  CloudflareAiMode,
  ExecutionMode,
  GraphPreviewTab,
  GroupBy,
  LaunchScope,
  Page,
  Requirement,
  Run,
  RunView,
  SortKey,
  TwinCondition,
  TwinFocus,
  TwinOverlay,
  TwinReport,
  TwinReviewItem,
  TwinRevision,
  Workspace,
} from './domain'
import { ExecutorStatus } from './executor'

export const Message = defineMessageUnion({
  SelectedGroupBy: { groupBy: GroupBy },
  ToggledGroup: { key: Schema.String },
  SelectedBulkOwner: { owner: Schema.String },
  ToggledPauseAfter: { wave: Schema.Number },
  ToggledLaunchAnother: {},
  ClickedRerun: {
    id: Schema.String,
    scope: Schema.Literals(['All', 'Failed']),
  },
  ClickedShortcuts: {},
  ClickedFinding: { runId: Schema.String, agentId: Schema.String },
  ClosedFinding: {},
  ClickedOutsidePanel: {},
  SteppedFinding: { direction: Schema.Literals(['Next', 'Previous']) },
  ToggledFindingSource: {},
  ClickedCopyFinding: {},
  CompletedCopyFinding: {},
  FailedCopyFinding: {},
  CompletedFocusFinding: {},
  SelectedRunFilter: {
    filter: Schema.Literals(['All', 'Running', 'Failed', 'Review']),
  },
  SelectedGraphPreviewTab: { tab: GraphPreviewTab },
  DismissedSetup: {},
  PressedTreeHandle: {},
  MovedTreeHandle: { y: Schema.Number },
  ReleasedTreeHandle: {},
  PressedTreeHandleKey: { key: Schema.String },
  ResetTreeHeight: {},
  PressedSidebarHandle: {},
  MovedSidebarHandle: { x: Schema.Number },
  ReleasedSidebarHandle: {},
  PressedSidebarHandleKey: { key: Schema.String },
  ResetSidebarWidth: {},
  LoadedSidebarWidth: { width: Schema.Number },
  CompletedSaveSidebarWidth: {},
  CompletedRevealGraphNode: {},
  CompletedExitMotion: {
    surface: Schema.Literals(['Toast', 'Inspector', 'Modal', 'Finding']),
    token: Schema.Number,
  },
  SelectedPage: { page: Page },
  LoadedNavigation: { page: Page, scrollTop: Schema.Number },
  CompletedSaveNavigation: {},
  CompletedRestoreScroll: {},
  OpenedArtifact: { id: Schema.String },
  OpenedAgent: { id: Schema.String },
  SelectedInbox: {},
  CompletedScrollToInbox: {},
  CompletedScrollActiveNav: {},
  SelectedArtifactView: { artifactView: ArtifactView },
  ToggledArtifactGroup: { id: Schema.String },
  ClickedArtifactFields: {},
  ToggledArtifactField: { field: ArtifactField },
  ClickedImport: {},
  UpdatedImportJson: { jsonText: Schema.String },
  SubmittedImport: {},
  UpdatedSearch: { value: Schema.String },
  SelectedFilter: { value: Schema.String },
  SelectedDisciplineView: { value: Schema.String },
  SelectedNode: { id: Schema.String },
  ClosedInspector: {},
  PressedGraphCanvas: { x: Schema.Number, y: Schema.Number },
  MovedGraphPan: { x: Schema.Number, y: Schema.Number },
  ReleasedGraphPan: {},
  ClickedGraphBackdrop: {},
  CompletedPanGraph: {},
  AcknowledgedConsent: {},
  SelectedRun: { id: Schema.String },
  ClickedNewBranch: {},
  SubmittedBranch: {},
  SelectedBranch: { id: Schema.String },
  ClickedMergeBranch: { id: Schema.String },
  DecidedBranchReview: {
    id: Schema.String,
    reviewStatus: Schema.Literals(['Approved', 'Rejected']),
  },
  ClickedNewRequirement: {},
  ClickedEditRequirement: { id: Schema.String },
  UpdatedTitle: { value: Schema.String },
  UpdatedDescription: { value: Schema.String },
  UpdatedOwner: { value: Schema.String },
  UpdatedKind: { value: Schema.String },
  ToggledLink: { id: Schema.String },
  SubmittedRequirement: {},
  ClickedNewAgent: {},
  ClickedEditAgent: { id: Schema.String },
  UpdatedInstructions: { value: Schema.String },
  SelectedAgentWave: { wave: AgentWave },
  SubmittedAgent: {},
  ToggledAgent: { id: Schema.String },
  ClickedLaunch: {},
  SelectedExecutionMode: { mode: ExecutionMode },
  CompletedProbeExecutor: { status: ExecutorStatus },
  FailedProbeExecutor: { error: Schema.String },
  CompletedPrepareCloudflareRun: {
    id: Schema.String,
    token: Schema.Number,
    runId: Schema.String,
  },
  FailedPrepareCloudflareRun: { id: Schema.String, token: Schema.Number },
  CompletedSyncCloudflareRun: {
    id: Schema.String,
    token: Schema.Number,
    run: Run,
  },
  FailedSyncCloudflareRun: {
    id: Schema.String,
    token: Schema.Number,
    error: Schema.String,
  },
  CompletedPendingCloudflareRun: { id: Schema.String, token: Schema.Number },
  ClickedReconnectRun: { id: Schema.String },
  ClickedRetryCloudflareDispatch: { id: Schema.String },
  ClickedProbeExecutor: {},
  UpdatedRunTarget: { id: Schema.String },
  SubmittedRun: {},
  CompletedSimulationWave: { id: Schema.String, token: Schema.Number },
  ClickedPauseRun: { id: Schema.String },
  ClickedResumeRun: { id: Schema.String },
  ClickedCancelRun: { id: Schema.String },
  SelectedRunView: { view: RunView },
  UpdatedRunLogQuery: { value: Schema.String },
  SelectedLaunchScope: { scope: LaunchScope },
  ToggledApprovalViewed: { id: Schema.String },
  StagedApprovalDecision: {
    id: Schema.String,
    decision: Schema.Literals(['Approved', 'Rejected']),
  },
  UpdatedDismissReason: { id: Schema.String, value: Schema.String },
  SubmittedReview: {},
  ClearedReview: {},
  ClickedApprove: { id: Schema.String },
  ClickedReject: { id: Schema.String },
  ClickedIntegration: { name: Schema.String },
  ClosedModal: {},
  DismissedToast: {},
  CompletedLoadWorkspace: { workspace: Workspace, restored: Schema.Boolean },
  FailedLoadWorkspace: { error: Schema.String },
  CompletedSaveWorkspace: {},
  FailedSaveWorkspace: { error: Schema.String },
  ClickedExport: {},
  CompletedExport: {},
  FailedExport: { error: Schema.String },
  ClickedGraphZoom: { direction: Schema.Literals(['In', 'Out', 'Reset']) },
  ClickedSortColumn: { key: SortKey },
  ToggledArtifactSelection: { id: Schema.String },
  ToggledAllArtifacts: {},
  ClickedClearSelection: {},
  SelectedBulkStatus: { status: Requirement.fields.status },
  SelectedAgent: { id: Schema.String },
  ToggledSidebar: {},
  ToggledWorkspaceMenu: {},
  ClosedWorkspaceMenu: {},
  PressedCommandPalette: {},
  UpdatedPaletteQuery: { value: Schema.String },
  MovedPaletteHighlight: { delta: Schema.Number },
  SubmittedPalette: {},
  ChosePaletteItem: { index: Schema.Number },
  CompletedFocusPalette: {},
  PressedPageShortcut: { page: Page },
  PressedArtifactShortcut: {
    action: Schema.Literals(['Next', 'Previous', 'Toggle', 'Edit']),
  },
  ClickedLoadTwinScenario: {},
  SelectedTwinFocus: { focus: TwinFocus },
  SelectedTwinOverlay: { overlay: TwinOverlay },
  SelectedTwinCondition: { condition: TwinCondition },
  ClickedTwinPart: { part: Schema.String },
  ClickedInstallTwinRevision: { revision: TwinRevision },
  ToggledTwinReview: { item: TwinReviewItem },
  ClickedGenerateTwinPackage: {},
  DraftedTwinReports: { files: Schema.Array(TwinReport) },
  SelectedTwinReport: { name: Schema.String },
  EditedTwinReport: { name: Schema.String, markdown: Schema.String },
  ClickedDownloadTwinPackage: {},
  LoadedTwinReports: { files: Schema.Array(TwinReport) },
  ElapsedTwinReportSave: { token: Schema.Number },
  SavedTwinReports: { token: Schema.Number },
  FailedSaveTwinReports: { token: Schema.Number },
  GeneratedTwinPackage: {
    name: Schema.String,
    digest: Schema.String,
    bytes: Schema.Number,
    files: Schema.Array(Schema.String),
  },
  FailedTwinPackage: { error: Schema.String },
  ClickedMarkTwinPackageSent: {},
  ClickedTraceTwinArtifact: { id: Schema.String },
  UpdatedCloudflareAccountId: { value: Schema.String },
  UpdatedCloudflareToken: { value: Schema.String },
  SubmittedCloudflareCredentials: {},
  ClickedForgetCloudflareCredentials: {},
  ClickedTestCloudflareCredentials: {},
  LoadedCloudflareCredentials: {
    accountId: Schema.String,
    hasToken: Schema.Boolean,
    mode: CloudflareAiMode,
  },
  CompletedCloudflareTest: {
    ok: Schema.Boolean,
    detail: Schema.String,
    latencyMs: Schema.Number,
  },
})
export type Message = typeof Message.Type
